/* =====================================================================
   LESSON DATA
   =====================================================================

   This is the only file SKILL.md needs to write. App code never changes.

   Lesson text may include these safe, attribute-free HTML tags:
   <br>, <i>, <em>, <b>, <strong>, <u>, <s>, <sub>, <sup>, <small>, <mark>.

   Each phrase references a CLIP ID (e.g. "01"), not a file path.
   Timings live in audio/<id>/sprite.json, generated by build-audio.sh.
   That means you can regenerate audio without touching this file, and
   edit this file without regenerating audio.

   THE NUMBER IS AN IDENTITY, NOT A POSITION. To add a phrase later, give
   it the next unused number and append it — never insert it in the middle
   and renumber. Renumbering keeps every filename valid while silently
   moving what each one means. audio/<id>/manifest.json records the text
   each clip was cut for, and verify.py fails if that drifts.

   ===================================================================== */

const LESSONS = [
  {
    id: "01",

    titleJapanese: "レッスン 01",
    titleBurmese: "နှုတ်ဆက်စကားနှင့် ယဉ်ကျေးမှုစကားများ",
    titleEnglish: "Greetings and polite expressions",

    phrases: [
      {
        clip: "01",
        japanese: "おはよう",
        romaji: "ohayō",
        burmese: "မင်္ဂလာနံနက်ခင်းပါ (ခင်မင်သူအချင်းချင်းသုံးတဲ့စကား)",
        english: "Good morning.",
      },
      {
        clip: "02",
        japanese: "おはようございます",
        romaji: "ohayō gozaimasu (ယဥ်ယဥ်ကျေးကျေးသုံးတဲ့စကား)",
        burmese: "မင်္ဂလာနံနက်ခင်းပါ",
        english: "Good morning.",
      },
      {
        clip: "03",
        japanese: "こんにちは",
        romaji: "konnichiwa",
        burmese: "မင်္ဂလာပါ / မင်္ဂလာနေ့လည်ခင်းပါ",
        english: "Hello. / Good afternoon.",
      },
      {
        clip: "04",
        japanese: "こんばんは",
        romaji: "konbanwa",
        burmese: "မင်္ဂလာညနေခင်းပါ",
        english: "Good evening.",
      },
      {
        clip: "05",
        japanese: "じゃあ、また",
        romaji: "jaa, mata",
        burmese: "သွားတော့မယ်",
        english: "See you / Bye.",
      },
      {
        clip: "06",
        japanese: "おさきに",
        romaji: "osaki ni",
        burmese:
          "မင်းထက်အရင်သွားတော့မယ် / ရှေ့ကနေ သွားပါ (သူငယ်ချင်းအခြင်းခြင်းသုံးတဲ့စကား)",
        english: "Leaving before you / Go ahead.",
      },
      {
        clip: "07",
        japanese: "しつれいします",
        romaji: "shitsurei shimasu",
        burmese: "ခွင့်ပြုပါ",
        english: "Excuse me.",
      },
      {
        clip: "08",
        japanese: "おさきにしつれいします",
        romaji: "osaki ni shitsurei shimasu",
        burmese:
          "ခွင့်ပြုပါ ၊ မင်းထက်အရင်သွားတော့မယ် (အလုပ်ကပြန်တဲ့အခါသုံးတဲ့စကား)",
        english: "I'm leaving before you (used when leaving the workplace)",
      },
      {
        clip: "09",
        japanese: "おつかれさまでした",
        romaji: "otsukaresama deshita",
        burmese:
          "သင်၏ ကြိုးစားအားထုတ်မှုအတွက် ကျေးဇူးတင်ပါတယ် (အလုပ်မှာ ယဥ်ကျေးစွာသုံတဲ့စကား)",
        english:
          "Thank you for your hard work. (polite, used in the workplace)",
      },
      {
        clip: "10",
        japanese: "おやすみ",
        romaji: "oyasumi",
        burmese: "မင်္ဂလာညပါ",
        english: "Good night.",
      },
      {
        clip: "11",
        japanese: "おやすみなさい",
        romaji: "oyasuminasai",
        burmese: "မင်္ဂလာညပါ (ယဥ်ကျေးစွာနှုတ်ဆက်ခြင်း)",
        english: "Good night. (polite)",
      },
      {
        clip: "12",
        japanese: "ありがとう",
        romaji: "arigatō",
        burmese: "ကျေးဇူးဘဲ (သူငယ်ချင်းအခြင်းခြင်းသုံးတဲ့စကား)",
        english: "Thank you.",
      },
      {
        clip: "13",
        japanese: "ありがとうございます",
        romaji: "arigatō gozaimasu",
        burmese: "ကျေးဇူးတင်ပါတယ် (ယဥ်ကျေးစွာပြောဆိုခြင်း)",
        english: "Thank you.",
      },
      {
        clip: "14",
        japanese: "どうもありがとう",
        romaji: "dōmo arigatō",
        burmese: "ကျေးဇူးအများကြီးတင်ပါတယ်",
        english: "Thank you very much.",
      },
      {
        clip: "15",
        japanese: "すみません",
        romaji: "sumimasen",
        burmese:
          "ကျေးဇူးပြု၍ / ဆောရီးပါ / ကျေးဇူးတင်ပါတယ်<br>(အသေးအမွှားကိစ္စကို ဝန်ခံခြင်း ၊ တစုံတဦးရဲ့ အာရုံစိုက်မှုကို ရယူခြင်း ၊ အကူအညီတခုအတွက် ကျေးဇူးတင်ခြင်း)",
        english:
          "Excuse me. / Sorry. / Thank you.<br>(to acknowledge a minor fault, get someone's attention, or show appreciation for help)",
      },
      {
        clip: "16",
        japanese: "どうぞ",
        romaji: "dōzo",
        burmese: "ရော့ဒီမှာ / ဆက်လုပ်ပါ",
        english: "Here you go. / Please go ahead.",
      },
      {
        clip: "17",
        japanese: "はい",
        romaji: "hai",
        burmese: "ဟုတ်တယ်",
        english: "Yes.",
      },
      {
        clip: "18",
        japanese: "いいえ",
        romaji: "iie",
        burmese: "မဟုတ်ဘူး",
        english: "No.",
      },
      {
        clip: "19",
        japanese: "ごめん",
        romaji: "gomen",
        burmese: "ဆောရီးပါ",
        english: "Sorry.",
      },
    ],
  },
  {
    id: "02",

    titleJapanese: "レッスン 02",
    titleBurmese: "နားလည်ခြင်း",
    titleEnglish: "Understanding",

    phrases: [
      {
        clip: "01",
        japanese: "わかりますか",
        romaji: "wakarimasu ka",
        burmese: "နားလည်လား",
        english: "Do you understand?",
      },
      {
        clip: "02",
        japanese: "はい、わかります",
        romaji: "hai, wakarimasu",
        burmese: "ဟုတ်ကဲ့။ နားလည်ပါတယ်",
        english: "Yes, I understand.",
      },
      {
        clip: "03",
        japanese: "いいえ、わかりません",
        romaji: "iie, wakarimasen",
        burmese: "မဟုတ်ဘူး။ နားမလည်ပါဘူး",
        english: "No, I don't understand.",
      },
      {
        clip: "04",
        japanese: "すこし",
        romaji: "sukoshi",
        burmese: "အနည်းငယ်",
        english: "a little",
      },
      {
        clip: "05",
        japanese: "すこしわかります",
        romaji: "sukoshi wakarimasu",
        burmese: "အနည်းငယ် နားလည်ပါတယ်",
        english: "I understand a little.",
      },
      {
        clip: "06",
        japanese: "にほんご",
        romaji: "nihongo",
        burmese: "ဂျပန်ဘာသာစကား",
        english: "Japanese language",
      },
      {
        clip: "07",
        japanese: "にほんごがわかります",
        romaji: "nihongo ga wakarimasu",
        burmese: "ဂျပန်စကား နားလည်ပါတယ်",
        english: "I understand Japanese.",
      },
      {
        clip: "08",
        japanese: "にほんごがすこしわかります",
        romaji: "nihongo ga sukoshi wakarimasu",
        burmese: "ဂျပန်စကား အနည်းငယ် နားလည်ပါတယ်",
        english: "I understand a little Japanese.",
      },
      {
        clip: "09",
        japanese: "よく",
        romaji: "yoku",
        burmese: "ကောင်းကောင်း",
        english: "well",
      },
      {
        clip: "10",
        japanese: "よくわかりません",
        romaji: "yoku wakarimasen",
        burmese: "ကောင်းကောင်း နားမလည်ပါဘူး",
        english: "I don't understand well.",
      },
      {
        clip: "11",
        japanese: "もういちど",
        romaji: "mō ichido",
        burmese: "နောက်တခေါက်",
        english: "once more",
      },
      {
        clip: "12",
        japanese: "おねがいします",
        romaji: "onegaishimasu",
        burmese: "ကျေးဇူးပြု၍ (လိုချင်တာ / အကူအညီလိုတာ)",
        english: "Please.",
      },
      {
        clip: "13",
        japanese: "すみません。もういちど、おねがいします",
        romaji: "sumimasen. mō ichido, onegaishimasu",
        burmese: "ခွင့်လွှတ်ပါ။ ကျေးဇူးပြု၍ နောက်တခေါက်",
        english: "Excuse me. Once more, please.",
      },
      {
        clip: "14",
        japanese: "もうすこし",
        romaji: "mō sukoshi",
        burmese: "နည်းနည်း ပိုပြီး",
        english: "a little more",
      },
      {
        clip: "15",
        japanese: "ゆっくり",
        romaji: "yukkuri",
        burmese: "ဖြည်းဖြည်းချင်း",
        english: "slowly",
      },
      {
        clip: "16",
        japanese: "いって",
        romaji: "itte",
        burmese: "ပြောပါ",
        english: "to say",
      },
      {
        clip: "17",
        japanese: "ください",
        romaji: "kudasai",
        burmese: "ကျေးဇူးပြု၍ ပေးပါ / လုပ်ပေးပါ",
        english: "Please. (to give or do something)",
      },
      {
        clip: "18",
        japanese: "ゆっくりいってください",
        romaji: "yukkuri itte kudasai",
        burmese: "ကျေးဇူးပြု၍ ဖြည်းဖြည်းချင်း ပြောပေးပါ",
        english: "Please speak slowly.",
      },
      {
        clip: "19",
        japanese: "すみません。もうすこし、ゆっくりいってください",
        romaji: "sumimasen. mō sukoshi, yukkuri itte kudasai",
        burmese:
          "ခွင့်လွှတ်ပါ။ ကျေးဇူးပြု၍ နည်းနည်းလောက် ပိုဖြည်းဖြည်း ပြောပေးပါ",
        english: "Excuse me, please speak a little more slowly.",
      },
      {
        clip: "20",
        japanese: "わかりました",
        romaji: "wakarimashita",
        burmese: "နားလည်သွားပါပြီ / ရသွားပြီ",
        english: "I understood. / I got it.",
      },
    ],
  },
];
